### ISSUE TITLE
Space in photo file name

### ISSUE THREAD

**Issue by nicksuch** [maymeclayton/maymeclayton.github.io#1]
Hey @maymeclayton - nice job with your web page! One tip to make it better is to avoid using spaces and capitalization in image filenames. Here's a reference on that: https://www.dummies.com/web-design-development/site-development/how-to-name-html-files/

This issue is that `Family Photo.jpg` actually becomes https://maymeclayton.github.io/Family%20Photo.jpg when interpreted by our web browser. The `%20` is HTML encoding for "space". In general, it's better to format file names like _Family-Photo.jpg_, and better yet is _family-photo.jpg_ because capitalization matters for file names, and it tends to be easiest to consistently make everything lowercase. In JavaScript, you'll get to something called CamelCase...but don't worry about that for now :)

If you ever want to check your HTML code for syntax errors, you can us this tool: https://validator.w3.org/nu/?doc=https://maymeclayton.github.io/

**Comment by maymeclayton** [comment]
I think I just fixed this... working on my Git and Command line skills this evening :)
